"""Настройки игры (без зависимостей от UI)."""

from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT_DIR / "data"

FPS = 60
WINDOW_WIDTH = 720
WINDOW_HEIGHT = 560

BASE_FLASH_MS = 450
BASE_GAP_MS = 180
ANSWER_TIME_SEC = 12.0
LIVES_START = 3
TEMPO_STEP_EVERY = 5
TEMPO_MULTIPLIER = 1.5

STREAK_FOR_SKIP = 3
ERROR_WINDOW = 5
ERROR_THRESHOLD = 3

HINT_DURATION_MS = 1200
MESSAGE_DURATION_MS = 2000
TIMEOUT_MESSAGE_MS = 1500
PLAYBACK_START_DELAY_MS = 400

MAX_RECORDS = 10
LEVEL_SELECT_COUNT = 10
COLOR_COUNT = 4
